# Generated by Django 2.2.28 on 2023-08-04 09:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('intern_management', '0001_initial'),
    ]

    default_session_year_id = 1

    operations = [
        migrations.AddField(
            model_name='headquarter',
            name='session_year_id',
            field=models.ForeignKey(default=default_session_year_id, on_delete=django.db.models.deletion.CASCADE, to='intern_management.SessionYearModel'),
        ),
    ]
