# Generated by Django 4.2.3 on 2023-07-21 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intern_management', '0002_studentresult_notificationstaffs_notificationintern_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentResult',
            new_name='InternResult',
        ),
    ]
