# Generated by Django 4.2.3 on 2023-07-22 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intern_management', '0004_alter_headquarter_department_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedbackintern',
            old_name='intren_id',
            new_name='intern_id',
        ),
    ]
