# Generated by Django 4.2.3 on 2023-07-22 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intern_management', '0005_rename_intren_id_feedbackintern_intern_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headquarter',
            name='staff_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intern_management.staffs'),
        ),
    ]
