# Generated by Django 4.2.3 on 2023-07-22 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intern_management', '0008_alter_headquarter_staff_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='headquarter',
            old_name='Headquarter_name',
            new_name='headquarter_name',
        ),
    ]
