# Generated by Django 4.2.3 on 2023-07-23 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intern_management', '0009_rename_headquarter_name_headquarter_headquarter_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='department_name',
            field=models.CharField(max_length=255, verbose_name='department name'),
        ),
        migrations.AlterField(
            model_name='headquarter',
            name='headquarter_name',
            field=models.CharField(max_length=255, verbose_name='headquarter name'),
        ),
    ]
