# Generated by Django 4.2.3 on 2023-07-24 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intern_management', '0010_alter_department_department_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminhod',
            name='address',
            field=models.TextField(verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='feedbackintern',
            name='feedback',
            field=models.TextField(verbose_name='feedback'),
        ),
        migrations.AlterField(
            model_name='feedbackintern',
            name='feedback_reply',
            field=models.TextField(verbose_name='feedback reply'),
        ),
        migrations.AlterField(
            model_name='feedbackstaffs',
            name='feedback',
            field=models.TextField(verbose_name='feedback'),
        ),
        migrations.AlterField(
            model_name='feedbackstaffs',
            name='feedback_reply',
            field=models.TextField(verbose_name='feedback reply'),
        ),
        migrations.AlterField(
            model_name='headquarter',
            name='headquarter_name',
            field=models.CharField(max_length=255, verbose_name='assignment name'),
        ),
        migrations.AlterField(
            model_name='intern',
            name='gender',
            field=models.CharField(max_length=50, verbose_name='gender'),
        ),
        migrations.AlterField(
            model_name='intern',
            name='profile_pic',
            field=models.FileField(upload_to='', verbose_name='profile picture'),
        ),
        migrations.AlterField(
            model_name='leavereportintern',
            name='leave_message',
            field=models.TextField(verbose_name='leave message'),
        ),
        migrations.AlterField(
            model_name='leavereportstaff',
            name='leave_date',
            field=models.CharField(max_length=255, verbose_name='leave date'),
        ),
        migrations.AlterField(
            model_name='leavereportstaff',
            name='leave_message',
            field=models.TextField(verbose_name='leave message'),
        ),
        migrations.AlterField(
            model_name='notificationintern',
            name='message',
            field=models.TextField(verbose_name='message'),
        ),
        migrations.AlterField(
            model_name='notificationstaffs',
            name='message',
            field=models.TextField(verbose_name='message'),
        ),
        migrations.AlterField(
            model_name='staffs',
            name='address',
            field=models.TextField(verbose_name='address'),
        ),
    ]
